name: 疯狂JOY挂机(自动)

on:
    workflow_dispatch:
    repository_dispatch:
        types: schedule

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【疯狂JOY挂机】"
              run: |
                  node schedule.js
              env:
                  #推送专用
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  #通用配置
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}
                  DO_NOT_FORK: ${{ github.event.client_payload.DO_NOT_FORK || secrets.DO_NOT_FORK }}
                  #GITHUB TOKEN
                  ACTIONS_TRIGGER_TOKEN: ${{ secrets.ACTIONS_TRIGGER_TOKEN }}
                  REPO: ${{ secrets.REPO }}
                  GITHUBUSER: ${{ secrets.GITHUBUSER }}
                  TRIGGER_KEYWORDS: ${{ secrets.TRIGGER_KEYWORDS }}
                  #CRONTAB
                  CRONTAB: ${{ '0 0 */6 * * *' }} #每6小时触发一次
                  GITHUB: ${{ github.event.client_payload.GITHUB || secrets.GITHUB }}
                  SYNCURL: https://github.com/an0na/jd_scripts_new/raw/master/jd_crazy_joy_coin.js #此处填写你要执行的js
